name: build-wheels-mac
description: Build Slicer Core and Slicer Core SDK for MacOS

on:
  workflow_call:
    inputs:
      vtk-tag:
        description: 'VTK version to use, must match the one in pyproject.toml'
        required: true
        type: string
      python-version:
        description: 'Python version to build (e.g., 3.10)'
        required: true
        type: string
      use-cache:
        description: 'Enable or disable build cache restoration and saving'
        type: boolean
        default: true
        required: true

jobs:
  build-test:
    runs-on: macos-15
    
    env:
      MACOSX_DEPLOYMENT_TARGET: "11.0"

    steps:
    - name: ccache config
      if: ${{ inputs.use-cache }}
      run: |
        brew install ccache zstd
        ccache --set-config=max_size=768Mi && ccache --set-config=compression=true
        echo "CMAKE_C_COMPILER_LAUNCHER=ccache" >> $GITHUB_ENV
        echo "CMAKE_CXX_COMPILER_LAUNCHER=ccache" >> $GITHUB_ENV

    - name: Restore ccache
      if: ${{ inputs.use-cache }}
      uses: actions/cache/restore@v4
      with:
        path: ~/Library/Caches/ccache
        key: ccache-${{ runner.os }}-${{ github.run_id }}
        restore-keys: ccache-${{ runner.os }}-

    # Build and test wheels
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Setup python depdencies
      run: pip install
        scikit-build-core
        vtk-sdk-python-wheel-helper
        cmake
        ninja
        pytest
        virtualenv
        vtk-sdk==${{ inputs.vtk-tag }}
        --extra-index-url https://vtk.org/files/wheel-sdks
        vtk==${{ inputs.vtk-tag }}
        --extra-index-url https://wheels.vtk.org

    - name: Apply patch
      run: |
        python apply_patch.py
        python set_vtk_version.py ${{ inputs.vtk-tag }}

    - name: Build runtime wheel
      run: python -m pip wheel ./Slicer/SlicerCore --wheel-dir ./wheelhouse --no-build-isolation

    - name: Test runtime wheel
      run: python -m pytest ./Slicer/SlicerCore --local-wheels=./wheelhouse -m runtime --verbose

    - name: sccache stats (after Runtime build)
      if: ${{ inputs.use-cache }}
      run: |
        ccache -s
        ccache -z

    - name: Upload wheel artifact
      uses: actions/upload-artifact@v4
      with:
        name: slicer_core-${{ runner.os }}_${{ inputs.python-version }}_${{ runner.arch }}
        path: wheelhouse/slicer_core-*.whl

    - name: Build SDK wheel
      run: python -m pip wheel ./Slicer/SlicerCoreSDK --wheel-dir ./wheelhouse --no-build-isolation

    - name: ccache stats (after SDK build)
      if: ${{ inputs.use-cache }}
      run: ccache -s -v

    - name: Upload wheel SDK artifact
      uses: actions/upload-artifact@v4
      with:
        name: slicer_core_sdk-${{ runner.os }}_${{ inputs.python-version }}_${{ runner.arch }}
        path: wheelhouse/slicer_core_sdk-*.whl

    - name: Test SlicerCore SDK
      run: python -m pytest ./Slicer/SlicerCore --local-wheels=./wheelhouse -m sdk --verbose

    - name: Save ccache
      uses: actions/cache/save@v4
      # We want the cache to be updated regardless of success, but ONLY if caching is enabled
      if: ${{ always() && inputs.use-cache }}
      with:
        path: ~/Library/Caches/ccache
        key: ccache-${{ runner.os }}-${{ github.run_id }}
