name: Release

on: workflow_dispatch

jobs:
  release-first:
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, windows-latest, macos-15]
        py-abi: ['cp310']
        vtk-tag: ['9.6.0']
        include:
          # Python version to install on host
          - py-abi: cp310
            python-version: '3.10'
          # OS name to ciwheelbuild platform name
          - os: ubuntu-latest
            platform-tag: manylinux_2_28_x86_64
            build-target: "manylinux_x86_64"
          - os: windows-latest
            platform-tag: win_amd64
            build-target: "win_amd64"
          - os: macos-15
            platform-tag: macosx_11_0_arm64
            build-target: "macosx_arm64"
    uses: ./.github/workflows/build-wheels.yml
    with:
      os: ${{ matrix.os }}
      vtk-tag: ${{ matrix.vtk-tag }}
      build-target: ${{ matrix.py-abi }}-${{ matrix.build-target }}
      python-version: ${{ matrix.python-version }}
      platform-tag: ${{ matrix.platform-tag }}
      use-cache: true

  release-all:
    needs: release-first # wait for previous job
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, windows-latest, macos-15]
        py-abi: ['cp311', 'cp312', 'cp313']
        vtk-tag: ['9.6.0']
        include:
          # Python version to install on host
          - py-abi: cp311
            python-version: '3.11'
          - py-abi: cp312
            python-version: '3.12'
          - py-abi: cp313
            python-version: '3.13'
          # OS name to ciwheelbuild platform name
          - os: ubuntu-latest
            platform-tag: manylinux_2_28_x86_64
            build-target: "manylinux_x86_64"
          - os: windows-latest
            platform-tag: win_amd64
            build-target: "win_amd64"
          - os: macos-15
            platform-tag: macosx_11_0_arm64
            build-target: "macosx_arm64"
    uses: ./.github/workflows/build-wheels.yml
    with:
      os: ${{ matrix.os }}
      vtk-tag: ${{ matrix.vtk-tag }}
      build-target: ${{ matrix.py-abi }}-${{ matrix.build-target }}
      python-version: ${{ matrix.python-version }}
      platform-tag: ${{ matrix.platform-tag }}
      use-cache: true

  upload-github:
    name: Push SlicerCore release on github
    needs: [release-first, release-all]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download all wheel artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./wheelhouse
          merge-multiple: true # Flattens them into one directory

      - name: Show downloaded wheels
        run: ls ./wheelhouse

      - name: Publish Release and Attach Wheels
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          # Attach all the downloaded wheels to the GitHub Release page
          files: ./wheelhouse/*.whl

  upload-pypi:
    name: Push SlicerCore on PyPi
    needs: [release-first, release-all]
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/slicer-core
    permissions:
      id-token: write # IMPORTANT: mandatory for trusted publishing
      contents: write # IMPORTANT: mandatory for making GitHub Releases

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download all wheel artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./wheelhouse
          pattern: slicer_core-*
          merge-multiple: true # Flattens them into one directory

      - name: Show downloaded wheels
        run: ls ./wheelhouse

      # https://docs.pypi.org/trusted-publishers/using-a-publisher/
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
            packages-dir: ./wheelhouse

  upload-pypi-sdk:
    name: Push SlicerCoreSDK on PyPi
    needs: [release-first, release-all]
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/slicer-core-sdk
    permissions:
      id-token: write # IMPORTANT: mandatory for trusted publishing
      contents: write # IMPORTANT: mandatory for making GitHub Releases

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download all wheel artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./wheelhouse
          pattern: slicer_core_sdk-*
          merge-multiple: true # Flattens them into one directory

      - name: Show downloaded wheels
        run: ls ./wheelhouse

      # https://docs.pypi.org/trusted-publishers/using-a-publisher/
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
            packages-dir: ./wheelhouse
