name: CI Slicer Core

on:
  pull_request:
    branches:  [ main ]

jobs:
  build-test:
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, windows-latest, macos-15]
        vtk-tag: ['9.6.0']
        include: # OS name to ciwheelbuild platform name
          - os: ubuntu-latest
            platform-tag: manylinux_2_28_x86_64
            build-targets: "cp310-manylinux_x86_64"
          - os: windows-latest
            platform-tag: win_amd64
            build-targets: "cp310-win_amd64"
          - os: macos-15
            platform-tag: macosx_11_0_arm64
            build-targets: "cp310-macosx_arm64"
    uses: ./.github/workflows/build-wheels.yml
    with:
      os: ${{ matrix.os }}
      vtk-tag: ${{ matrix.vtk-tag }}
      build-targets: ${{ matrix.build-targets }}
      platform-tag: ${{ matrix.platform-tag }}
      macosx-deployment-target: "11.0"
